export const NEW_ORDER = 'NEW_ORDER';
export const ACCEPT_ORDER =  'ACCEPT_ORDER';
export const REJECT_ORDER = 'REJECT_ORDER';
export const COMMENCE_ORDER = 'COMMENCE_ORDER';
export const COMPLETE_ORDER = 'COMPLETE_ORDER';
